apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJWMmd4ZEdWWE1XNTBaWEk2WjJod1gzTk9RMEo0VlRWNE9VSmlSRkYzV2s1WWIyVjZhMVJ3WVdrMmJrUnlXRE5wYTNGak5nPT0iCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
