apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJWMmd4ZEdWWE1XNTBaWEk2WjJod1gxcDBaV3BPUzBGV1NFTlJSMnBQYzBaNmJIRkZUMHBLVld0WVpWWmlkek5JZURsMVlnPT0ifX19DQo=
type: kubernetes.io/dockerconfigjson
